-- use burgers2_db; 
-- INSERT INTO burgers (burger_name) VALUES ('Fish Burger');
-- INSERT INTO burgers (burger_name) VALUES ('Double Whooper');
-- INSERT INTO burgers (burger_name, devoured) VALUES ('Cheese Burger', true);
-- INSERT INTO burgers (burger_name, devoured) VALUES ('Juicy Lucy', true);
-- INSERT INTO burgers (burger_name, devoured) VALUES ('Rib Burger', true);
-- INSERT INTO burgers (burger_name) VALUES ('No Cheese Burger');
